-- Active: 1684524067416@@172.17.0.2@3306@School
INSERT INTO School.Students (id, name, age) VALUES ('1', 'John Smith', '20');
INSERT INTO School.Students (id, name, age) VALUES ('2', 'Jane Doe', '19');
INSERT INTO School.Students (id, name, age) VALUES ('3', 'Michael Johnson', '21');
INSERT INTO School.Students (id, name, age) VALUES ('4', 'Sarah Williams', '22');
INSERT INTO School.Students (id, name, age) VALUES ('5', 'David Brown', '18');
INSERT INTO School.Students (id, name, age) VALUES ('6', 'Emily Davis', '20');
INSERT INTO School.Students (id, name, age) VALUES ('7', 'James Wilson', '19');
INSERT INTO School.Students (id, name, age) VALUES ('8', 'Olivia Taylor', '21');
INSERT INTO School.Students (id, name, age) VALUES ('9', 'Robert Anderson', '22');
INSERT INTO School.Students (id, name, age) VALUES ('10', 'Sophia Martinez', '18');
INSERT INTO School.Students (id, name, age) VALUES ('11', 'William Thomas', '20');
INSERT INTO School.Students (id, name, age) VALUES ('12', 'Ava Jackson', '19');
INSERT INTO School.Students (id, name, age) VALUES ('13', 'Matthew White', '21');
INSERT INTO School.Students (id, name, age) VALUES ('14', 'Emma Harris', '22');
INSERT INTO School.Students (id, name, age) VALUES ('15', 'Liam Thompson', '18');
INSERT INTO School.Students (id, name, age) VALUES ('16', 'Isabella Martin', '20');
INSERT INTO School.Students (id, name, age) VALUES ('17', 'Christopher Garcia', '19');
INSERT INTO School.Students (id, name, age) VALUES ('18', 'Mia Lopez', '21');
INSERT INTO School.Students (id, name, age) VALUES ('19', 'Andrew Lee', '22');
INSERT INTO School.Students (id, name, age) VALUES ('20', 'Charlotte Clark', '18');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('1', 'Mathematics', '1', '2023-05-01');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('2', 'Mathematics', '2', '2023-05-01');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('3', 'Mathematics', '3', '2023-05-01');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('4', 'Mathematics', '4', '2023-05-01');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('5', 'Mathematics', '5', '2023-05-01');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('6', 'English', '1', '2023-05-02');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('7', 'English', '2', '2023-05-02');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('8', 'English', '3', '2023-05-02');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('9', 'English', '4', '2023-05-02');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('10', 'English', '5', '2023-05-02');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('11', 'Physics', '1', '2023-05-03');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('12', 'Physics', '2', '2023-05-03');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('13', 'Physics', '3', '2023-05-03');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('14', 'Physics', '4', '2023-05-03');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('15', 'Physics', '5', '2023-05-03');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('16', 'Chemistry', '1', '2023-05-04');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('17', 'Chemistry', '2', '2023-05-04');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('18', 'Chemistry', '3', '2023-05-04');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('19', 'Chemistry', '4', '2023-05-04');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('20', 'Chemistry', '5', '2023-05-04');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('21', 'History', '1', '2023-05-05');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('22', 'History', '2', '2023-05-05');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('23', 'History', '3', '2023-05-05');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('24', 'History', '4', '2023-05-05');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('25', 'History', '5', '2023-05-05');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('26', 'Geography', '1', '2023-05-06');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('27', 'Geography', '2', '2023-05-06');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('28', 'Geography', '3', '2023-05-06');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('29', 'Geography', '4', '2023-05-06');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('30', 'Geography', '5', '2023-05-06');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('31', 'Computer Science', '1', '2023-05-07');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('32', 'Computer Science', '2', '2023-05-07');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('33', 'Computer Science', '3', '2023-05-07');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('34', 'Computer Science', '4', '2023-05-07');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('35', 'Computer Science', '5', '2023-05-07');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('36', 'Art', '1', '2023-05-08');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('37', 'Art', '2', '2023-05-08');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('38', 'Art', '3', '2023-05-08');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('39', 'Art', '4', '2023-05-08');
INSERT INTO School.Attendance (id, course_name, student_id, date) VALUES ('40', 'Art', '5', '2023-05-08');
